[env:m5paper-v1]
platform = espressif32@6.10.0
board = m5stack_paper
framework = arduino
monitor_speed = 115200
build_flags =
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
lib_deps =
    m5stack/M5Unified@^0.2.8
    h2zero/NimBLE-Arduino@^2.3.7
    bblanchon/ArduinoJson@^7.3.1